---

- name: app-nginx-available
  template: src=site_assets.app.j2 dest=/etc/nginx/sites-available/assets.app owner=www-data group=www-data

- name: app-nginx-enable
  file: src=/etc/nginx/sites-available/assets.app dest=/etc/nginx/sites-enabled/assets.app state=link owner=www-data group=www-data
  notify:
    - restart nginx
 
